(function () {
  'use strict';

  const depth = (context, questions) => ({ context, questions });

  window.AccessibleFinanceGuideDepth = {
    'investing-vs-speculating': depth([
      'Put the distinction to work by giving every dollar a job before choosing an asset. Money for retirement, education, a home, or another important goal belongs in a goal-based portfolio with a time horizon, a target mix, and a contribution plan. Money reserved for a concentrated idea belongs in a separate speculation allowance. Keeping the two pools apart prevents a temporary trade from quietly becoming the plan for something you cannot afford to postpone.',
      'For any concentrated purchase, write a short thesis before placing the order. Name the source of the expected return, the evidence supporting it, the conditions that would prove it wrong, and the maximum amount you can lose. Review the quality of that reasoning after the outcome. A lucky gain built on a weak process is not evidence of skill, while a well-reasoned investment can still have a disappointing result.'
    ], [
      ['Does holding something for years make it an investment?', 'No. Time alone does not create productive value or repair a thesis that never had evidence behind it. A long holding period is useful when it allows earnings, interest, or broad economic growth to accumulate. Holding a price-driven bet indefinitely can simply turn a short-term speculation into a long-term loss.'],
      ['Is buying an individual stock always speculation?', 'Not automatically. A buyer may study the business, valuation, finances, and competitive position carefully. The position is still concentrated, however, so company-specific risk remains much higher than in a broad fund. Research can improve a thesis, but it cannot provide the diversification of owning many businesses.'],
      ['How much is reasonable to speculate with?', 'There is no universal percentage. Start only after near-term bills, emergency savings, expensive debt, and important long-term contributions are addressed. The right amount is one that could fall to zero without changing your housing, retirement date, education plan, or ability to sleep and continue the core strategy.']
    ]),

    'why-investing-exists': depth([
      'A practical investor looks through the account label to the financial claim underneath it. A stock fund owns slices of businesses; a bond fund owns promises from borrowers; a savings product is a claim on a financial institution. Each claim has a different place in line for cash flows and a different response to growth, inflation, interest rates, and failure. That is more useful than sorting products into a vague list of things that have recently gone up.',
      'Also separate the primary market from the secondary market. A company receives capital when it first issues shares or debt. Most everyday trades happen later between investors. Those secondary markets still matter because liquidity and observable prices make people more willing to supply capital in the first place. For your own plan, the central questions are what you own, what could generate the return, what risks can interrupt it, and whether the price is reasonable.'
    ], [
      ['Does buying an ETF directly fund the companies inside it?', 'Usually your trade is with another market participant, not a direct payment to each company. Even so, well-functioning secondary markets support the wider capital system by making ownership transferable and helping establish prices. Your personal return still comes from the securities the fund owns, after costs.'],
      ['Where do long-term investment returns come from?', 'They can come from interest paid by borrowers, dividends and retained profits from businesses, growth in those businesses, or a change in the price investors are willing to pay. A sound plan does not assume price increases appear from nowhere; it connects expectations to economic cash flows and risk.'],
      ['Why can a useful company still be a poor investment?', 'Price matters. An excellent business purchased at a price that assumes flawless future growth can disappoint even while the business remains successful. Investing requires two judgments: the quality and durability of the underlying activity, and the amount paid for the claim on that activity.']
    ]),

    'how-markets-work': depth([
      'Before trading, separate the investment decision from the execution decision. The investment decision asks whether the security fits your goal, risk, costs, and portfolio. Execution asks how to enter or leave without accepting an unnecessary price. Check the bid, ask, recent trading volume, and whether markets are moving unusually quickly. A familiar ticker can still trade poorly when activity is thin or news has disrupted normal liquidity.',
      'Use an order type deliberately. A market order prioritizes completion but leaves the final price uncertain. A limit order controls the worst acceptable price but may remain unfilled. For a recurring purchase of a liquid broad-market fund, the difference may be small; for a thin security or a large order, it can be meaningful. Record commissions, spreads, currency conversion, and taxes so the true cost of turnover is visible.'
    ], [
      ['Why did my trade fill above the price I saw?', 'The displayed quote may have been the last completed trade, while the next available seller was asking more. Quotes can also change between the moment you submit and the moment the order reaches the market. The difference is more noticeable in fast or lightly traded markets.'],
      ['Does zero commission mean a trade is free?', 'No. The bid-ask spread, foreign-exchange conversion, fund expenses, account fees, and tax consequences can all create costs. Frequent trading also creates an opportunity cost when attention and cash are repeatedly moved around without improving the underlying portfolio.'],
      ['Should a beginner always use limit orders?', 'Not as an absolute rule. A limit order is useful when price control matters, but it can fail to execute and leave the plan incomplete. Understand the liquidity of the security, avoid treating the current quote as a promise, and choose the order type that matches your actual priority.']
    ]),

    'what-risk-means': depth([
      'Build a risk inventory around the household rather than looking only at a questionnaire score. List when each goal must be funded, how flexible that date is, what income sources could weaken at the same time, and which expenses cannot be reduced. Then map the portfolio to those obligations. A volatile asset may be acceptable for a flexible goal decades away and unsuitable for a fixed payment next year.',
      'Keep three ideas separate: willingness to take risk, financial capacity to absorb loss, and the amount of risk required to reach the goal. Someone may feel comfortable with large swings but lack capacity because the money is needed soon. Another person may have decades of capacity but little emotional tolerance. A durable allocation respects the tightest constraint and does not require heroic behaviour during a crisis.'
    ], [
      ['Is volatility the same as risk?', 'Volatility measures how widely prices move, but personal risk is broader. It includes permanent loss, inflation, insufficient growth, concentration, leverage, fraud, poor liquidity, and being forced to sell at the wrong time. The relevant definition depends on what the money must accomplish.'],
      ['Can a conservative investment still be risky?', 'Yes. Cash can be very safe for next month while being risky for a retirement goal if inflation steadily reduces what it can buy. A long bond can fluctuate when interest rates change. Conservative should describe how an asset serves a specific goal, not merely how calm its price looked recently.'],
      ['How can I test my real tolerance for loss?', 'Translate percentages into dollars and decisions. Ask how you would respond if a $100,000 portfolio temporarily showed $75,000, your job felt less secure, and negative headlines continued for months. If the planned response is unclear, reduce risk or write explicit rebalancing and withdrawal rules before the stress arrives.']
    ]),

    'risk-and-return': depth([
      'Use expected return as a planning range, not a promised annual result. Higher-returning assets generally demand compensation for uncertainty, long holding periods, or the possibility of loss. That premium may disappear for years. A projection should therefore show a conservative case, a central case, and a stronger case, while contributions and spending remain the main levers you can actually control.',
      'Risk also changes with the direction of cash flow. A saver buying regularly can acquire more units after a decline. A retiree selling units may lock in the same decline and leave less capital for a recovery. When withdrawals are near, test the plan against an early market loss, several years of weak returns, and higher inflation rather than relying only on a smooth average.'
    ], [
      ['Does taking more risk guarantee a higher return?', 'No. Risk creates the possibility of compensation, not an entitlement to it. A concentrated or leveraged position can take enormous risk and still lose permanently. Diversification and a long horizon improve the odds of capturing broad market returns, but neither removes uncertainty.'],
      ['What return should I use in a calculator?', 'Use several assumptions and state whether they are before or after fees, taxes, and inflation. A plan that works only with an aggressive return deserves revision. Increasing savings, reducing the target, or allowing more time is usually more dependable than simply typing a larger return into the forecast.'],
      ['Why does the order of returns matter?', 'Deposits and withdrawals make the path important. A large loss early in retirement can be especially damaging because withdrawals remove units before a recovery. During accumulation, those same lower prices may help recurring contributions. Average return alone cannot show this sequence effect.']
    ]),

    'time-in-market': depth([
      'Replace predictions with rules. Decide the long-term asset mix, the contribution date, the rebalancing range, and the amount of cash needed outside the market. Those decisions determine how much exposure you hold without requiring a forecast about next month. When unsettling news arrives, compare the facts with the written rules instead of asking whether this particular headline feels different.',
      'Market timing is not one decision but two: when to leave and when to return. The second decision is often harder because prices can recover while economic news is still poor. If investing a large amount at once would make you abandon the plan, a short, predetermined schedule can be a reasonable behavioural compromise. The schedule should have dates and an end point so temporary caution does not become permanent cash.'
    ], [
      ['Is investing a lump sum always better than spreading it out?', 'Investing sooner gives money more time in the market, but it also exposes the full amount immediately. A staged plan may reduce regret and improve follow-through. The best method is one whose trade-off you understand and can complete without repeatedly changing the schedule in response to headlines.'],
      ['What if the market looks obviously overvalued?', 'Valuation can inform long-term expectations, but it does not provide a dependable short-term clock. Prices can remain expensive, become more expensive, or correct after years of waiting. Adjust risk through a suitable allocation and goal horizon rather than making the entire plan depend on one entry forecast.'],
      ['When is it reasonable to move out of the market?', 'A change can be justified when the goal date, spending need, income security, risk capacity, or target allocation has genuinely changed. It is different from selling solely because prices fell. Document the life change and the permanent allocation decision so it is not confused with a temporary prediction.']
    ]),

    'inflation-and-cash': depth([
      'Give cash more than one label. An operating balance covers current bills, an emergency reserve absorbs surprises, and short-term goal money protects a known purchase. Those jobs favour stability and access. Cash held for a distant goal has a different job and should be tested against inflation, taxes on interest, and the return available from assets that can tolerate more movement.',
      'Track goals in future purchasing power, not just future dollars. Estimate what the desired lifestyle, education cost, or home project might cost at the goal date, then test more than one inflation rate. This does not mean investing every dollar. It means accepting that price stability today and purchasing-power stability over decades are different forms of safety that belong in different buckets.'
    ], [
      ['How much cash should I keep?', 'The answer depends on essential monthly expenses, job stability, insurance, household income sources, and upcoming goals. A common emergency-fund starting point is several months of regular expenses, but the amount should grow when income is volatile or a major obligation cannot be delayed.'],
      ['Should emergency savings be invested to beat inflation?', 'Usually the first priority is reliable access without a forced sale. A high-interest savings account or suitable short-term deposit may not beat inflation every year, but it protects the fund\'s emergency function. Invest only the portion whose timing is flexible enough to withstand a decline.'],
      ['What is a real return?', 'Real return is the gain after accounting for inflation. If money earns 4% while prices rise 3%, purchasing power grows by roughly 1% before tax, using a simple approximation. Real returns make goals across long periods easier to compare.']
    ]),

    'compound-interest': depth([
      'Make compounding visible with a small scenario table. Show the starting amount, recurring contribution, years, assumed return, fees, and inflation. Then run lower and higher return cases instead of presenting one precise future balance. Separating total contributions from projected growth helps explain where the result comes from and prevents a calculator from looking more certain than the real market.',
      'Focus first on the inputs you control. Contribution amount, contribution frequency, fees, taxes, and time are more actionable than next year\'s return. Revisit the projection after a meaningful income change or once a year, not after every market move. If the conservative scenario misses the goal, adjust savings, timing, or the goal itself before reaching for a riskier assumption.'
    ], [
      ['Is compound interest the same for investments and savings accounts?', 'The mathematics is similar, but the return pattern is not. A savings rate may be stated and relatively stable for a period. Investment returns vary and can be negative. Use compound-growth illustrations for planning, not as a schedule of what a portfolio will earn each year.'],
      ['Why does my balance grow slowly at first?', 'Early in the journey, the balance is small, so even a good percentage return creates a modest dollar amount. Contributions do most of the work. As the base grows, returns can become larger than new deposits, but reaching that stage requires time and consistency.'],
      ['How often should compounding be calculated?', 'The stated compounding frequency matters for guaranteed products, but for a market portfolio it is less important than using a realistic long-term return after costs. Monthly calculations can align with contributions, while annual summaries are often easier to understand and review.']
    ]),

    'starting-early': depth([
      'Starting early should lower pressure, not create guilt. Choose an amount that can survive an ordinary month and automate it. Increase the amount after raises or when debt payments end. A durable $50 contribution teaches the account mechanics and establishes a repeatable habit; an ambitious $500 plan that is cancelled after two months does not create the same foundation.',
      'Balance the benefit of time with the rest of the household. Build a basic emergency buffer, make required debt payments, and capture any valuable employer match before taking avoidable investment risk. Then connect each contribution to a named goal. A clear goal makes it easier to decide whether the account, asset mix, and time horizon still make sense as life changes.'
    ], [
      ['Is it too late to start in my forties or fifties?', 'No. The plan may require a higher savings rate, a later goal date, lower future spending, or some combination, but starting now still improves the outcome. Use current numbers and available time rather than comparing yourself with an idealized person who began decades earlier.'],
      ['Should I invest while paying off debt?', 'Compare the guaranteed interest avoided by repaying debt with the uncertain after-tax return from investing, while preserving liquidity and any employer match. High-cost debt often deserves priority. Lower-cost debt leaves more room for a blended approach based on risk and cash flow.'],
      ['What if I can afford only a very small amount?', 'A small automated contribution is still useful when fees do not consume it. It builds the process and can rise later. The more important early step may be stabilizing bills, creating a cash buffer, or increasing income so the future contribution has room to grow.']
    ]),

    'dollar-cost-averaging': depth([
      'Separate automatic investing from the decision about an existing lump sum. Investing part of every paycheque is naturally spread through time because the money arrives gradually. Holding a large amount of available cash and moving it in slowly is a different choice: it reduces immediate exposure and regret, but may sacrifice returns if markets rise during the schedule.',
      'If a staged approach helps you act, define it in advance. Set the amount, dates, eligible investment, and final date. Continue through both rising and falling markets. The plan fails when each instalment becomes a new prediction contest, because fear can suspend purchases after a decline and excitement can accelerate them after prices have already risen.'
    ], [
      ['Does dollar-cost averaging prevent losses?', 'No. It changes the purchase prices paid over time but does not guarantee a profit or protect the final balance. If the investment falls and never recovers, recurring purchases can also lose money. The underlying asset still needs to fit the goal.'],
      ['Should I stop automatic purchases during a downturn?', 'A downturn is when the same contribution buys more units. Stopping solely because prices fell reverses the method. Pause only when cash flow, emergency needs, debt, the goal, or the suitability of the investment has changed, not because the regular schedule feels uncomfortable.'],
      ['What contribution frequency is best?', 'Match the schedule to cash flow and keep trading costs in mind. Investing soon after each paycheque is simple and limits idle cash. Weekly versus monthly frequency is usually less important than the contribution amount, low costs, and ability to continue.']
    ]),

    'dividend-reinvestment': depth([
      'Treat dividends as one component of total return, not a separate source of free money. On the ex-dividend date, other things equal, the share price adjusts to reflect cash leaving the company. What matters is the combined result of distributions and price change after fees and taxes. A high yield can reflect a mature business, a falling price, or a distribution that may not be sustainable.',
      'Choose reinvestment based on portfolio needs. During accumulation, an automatic dividend reinvestment plan can keep cash working and reduce small manual trades. During withdrawals, cash distributions may help fund spending. In either case, review the full allocation: reinvesting every payment into the same security can increase an already concentrated position and make rebalancing harder.'
    ], [
      ['Are dividends guaranteed?', 'Common-share dividends can be reduced or cancelled. A long history may show management\'s intention, but it does not create a contractual promise. Bond interest and preferred-share distributions have different legal features, yet they also carry issuer and market risks.'],
      ['Is a dividend portfolio safer than an index fund?', 'Not necessarily. Selecting only high-yield companies can concentrate the portfolio in a few sectors and exclude businesses that return value in other ways. Compare diversification, valuation, financial strength, taxes, and total return rather than using yield as a safety score.'],
      ['Do reinvested dividends still create tax?', 'In a taxable account, a distribution can generally be taxable even when it is immediately used to buy more units. Keep records and review the tax character of each distribution. Registered accounts have different rules, so account type matters.']
    ]),

    'rule-of-72': depth([
      'Use the Rule of 72 as a conversation starter, then move to a proper calculation for decisions. Divide 72 by an annual percentage to estimate a doubling period. The shortcut is most useful for moderate positive rates and smooth compounding. It becomes less accurate with very high rates, changing returns, recurring deposits, taxes, or withdrawals.',
      'Its real value is comparison. Estimate how quickly prices double under inflation, how long a debt balance would double without payments, or how fees change a portfolio\'s net growth rate. Then ask whether the rate is nominal or after inflation and whether it is guaranteed or merely assumed. Those labels matter more than an extra decimal place in the estimate.'
    ], [
      ['Why 72 instead of 70 or 69.3?', 'The mathematically exact constant for continuous compounding is close to 69.3, but 72 divides neatly by many common rates and gives a convenient approximation. The shortcut trades a little precision for mental arithmetic.'],
      ['Can I use the rule for investment forecasts?', 'Only as a rough illustration. Market returns are uneven, fees reduce the net rate, and taxes or withdrawals alter the path. Use a calculator with conservative assumptions for an actual goal, then compare the result with the Rule of 72 as a reasonableness check.'],
      ['Can the rule explain inflation?', 'Yes. At steady 3% inflation, the shortcut suggests prices double in about 24 years. Actual inflation varies and different goods rise at different rates, but the estimate makes the long-term effect of seemingly small annual price increases easier to grasp.']
    ]),

    'investment-fees': depth([
      'Create a complete fee inventory in both percentages and dollars. Include fund expenses, advice charges, account administration, trading commissions, bid-ask spreads, currency conversion, transfer fees, and any sales charges. Apply recurring percentages to the current balance and to a plausible future balance. A fee that looks minor on $10,000 can become a major annual expense after decades of contributions.',
      'Cost is not the same as value. Advice may include planning, tax coordination, behaviour coaching, or specialized portfolio work. Write down what service is being purchased, how often it is delivered, and how success will be evaluated. Compare alternatives with similar holdings and service levels. Before switching, include one-time tax, redemption, and transfer consequences so saving an annual fee does not create a larger immediate cost.'
    ], [
      ['Where do I find a fund\'s fees?', 'Start with the fund facts or prospectus and look for the management expense ratio and trading expense ratio. Then check the brokerage and adviser disclosures for charges outside the fund. Account statements may show some costs, but not every cost appears as a separate withdrawal.'],
      ['Is the lowest-fee fund always best?', 'No. The investment must still provide the right exposure, diversification, liquidity, tracking, and service. Among genuinely comparable products, lower recurring cost is a strong advantage because the saving is certain while future outperformance is not.'],
      ['How often should I review fees?', 'Review them at least annually and whenever the balance, adviser arrangement, fund class, or account provider changes. Express the result in dollars as well as percentages, and ask whether each recurring cost still provides a service or exposure the plan needs.']
    ]),

    'taxes-and-compounding': depth([
      'Evaluate investments on an after-tax, after-fee basis without letting tax become the only objective. Start with the goal and suitable asset mix, then choose among available account types and decide where different holdings belong. A tax-efficient structure cannot rescue an unsuitable or excessively risky investment, but repeated tax drag can meaningfully reduce the amount left to compound.',
      'Keep a simple map of each account: contribution deductibility, tax treatment of growth, withdrawal rules, room or limits, beneficiary details, and the records you must retain. For taxable holdings, track adjusted cost base and distribution details. Revisit the map after income, province, family status, or legislation changes. When the decision is material, verify current rules with the CRA or a qualified tax professional instead of relying on an old summary.'
    ], [
      ['Should taxes determine what I invest in?', 'Taxes are one input. Risk, diversification, time horizon, liquidity, and cost come first. Avoiding tax on a poor investment is not a good outcome, and selling solely for tax reasons can damage the larger plan. Compare the after-tax result while preserving the intended portfolio.'],
      ['Is tax deferral the same as tax elimination?', 'No. Deferral postpones tax and allows money that would otherwise leave the account to remain invested. The eventual withdrawal may still be taxable. Its value depends partly on the deduction received, future tax rate, time, and how the tax refund is used.'],
      ['When should I get professional tax help?', 'Consider help when dealing with a business, cross-border status, trusts, significant capital gains, estate planning, complex benefits, or large registered-account decisions. A professional can apply current rules to your facts; an educational article cannot determine your personal tax result.']
    ]),

    'stocks-explained': depth([
      'Analyze a stock in layers. First understand how the company makes money, who its customers are, what could strengthen or weaken demand, and how much debt it carries. Then review revenue, profit, free cash flow, margins, and the number of shares outstanding over several years. Finally compare those fundamentals with the market price. A good company and a reasonably priced stock are related questions, but they are not the same question.',
      'Decide the portfolio role before deciding the ticker. A single company can provide learning and potential upside, but it also creates risks that a broad fund spreads across hundreds or thousands of holdings. Set a maximum position size, a rule for employer stock, and a review schedule based on business evidence rather than daily price movement. If the thesis requires one product launch or one executive to be perfect, the position should reflect that fragility.'
    ], [
      ['Why can a stock rise when the company reports a loss?', 'The market price reflects expectations about the future, not only the latest period. A loss may be smaller than investors expected, or buyers may anticipate future growth. The reverse also happens: a profitable company can fall when results or guidance disappoint expectations already embedded in the price.'],
      ['What happens to shareholders if a company fails?', 'Creditors generally stand ahead of common shareholders. Assets are used to meet secured and other creditor claims before residual value reaches owners, so common shares can become worthless. Diversification limits how much one failure can affect the overall plan.'],
      ['How many individual stocks are enough?', 'There is no magic count because companies can share the same sector, geography, customers, or economic risks. A broad fund is a simpler diversification tool. If selecting individual companies, evaluate position weights and common exposures rather than counting ticker symbols alone.']
    ]),

    'bonds-explained': depth([
      'Read a bond as a contract. Identify the issuer, maturity date, coupon, payment currency, seniority, call features, and current yield. Then ask what could prevent full repayment and how the price would respond if market interest rates changed. A government bill due soon and a long-term lower-quality corporate bond may both be called fixed income, yet they solve very different problems.',
      'Match maturity to the job. Money needed soon may use short, high-quality instruments to limit price movement. A longer-term portfolio may hold a diversified bond fund for income, stability, and rebalancing capacity, while accepting that its price can fall. Compare yield after fees with credit and duration risk; a noticeably higher yield is usually compensation for something, not a free improvement.'
    ], [
      ['Why do bond prices fall when interest rates rise?', 'Existing bonds with lower coupons become less attractive than newly issued bonds paying more, so their market prices adjust downward. The effect is generally larger for longer maturities. If held to maturity and repaid, an individual bond still returns its stated principal, subject to default and contract terms.'],
      ['Can a bond fund mature like an individual bond?', 'Most broad bond funds continually replace maturing holdings and do not have one date when the entire fund repays principal. A target-maturity fund is different. Understand whether you need a known cash-flow date or ongoing diversified bond exposure.'],
      ['Are government bonds risk-free?', 'They may have very low default risk in their own currency, but their market prices can still change, inflation can reduce purchasing power, and foreign bonds add currency risk. Risk-free should always specify which risk and over what period.']
    ]),

    'mutual-funds-vs-etfs': depth([
      'Compare the actual products rather than assuming the wrapper determines quality. Check the mandate, holdings, benchmark, asset mix, management style, expense ratio, trading costs, minimum purchase, automatic contribution options, and tax treatment. A low-cost mutual fund can be more suitable than an expensive narrow ETF, while a broad low-cost ETF can be more efficient than a high-fee mutual fund.',
      'Fit the product to the workflow. Mutual funds transact at a calculated end-of-day value and often support exact-dollar automation. ETFs trade throughout the day and may require attention to spreads, order types, and whole or fractional units depending on the broker. For a long-term saver, the best wrapper is often the one that delivers the intended exposure at low total cost and makes the contribution plan easiest to maintain.'
    ], [
      ['Are ETFs always cheaper than mutual funds?', 'No. Many broad ETFs have low expenses, but specialized or actively managed ETFs can cost more. Some mutual funds are also low cost. Include advice, account, trading, spread, and currency costs rather than comparing only one published percentage.'],
      ['Does intraday trading make an ETF better?', 'It provides flexibility, but long-term investors may not need it. Intraday prices can encourage unnecessary trading and can differ slightly from underlying value. The feature is useful only when it serves the plan rather than inviting more decisions.'],
      ['Can I automate ETF purchases?', 'Many brokerages now support recurring purchases or fractional units, but features vary. Confirm eligible securities, timing, cash requirements, and fees. If automation is unavailable, schedule a simple recurring reminder and avoid letting small cash balances sit indefinitely.']
    ]),

    'index-funds': depth([
      'Start with the index methodology, not the word index. Learn which market the index covers, how securities enter and leave, how holdings are weighted, how often it rebalances, and whether one country or sector can dominate. Two funds labelled broad market can have very different exposures. The fund should fill a defined portfolio role rather than merely track a recognizable name.',
      'Then evaluate implementation. Compare the expense ratio, tracking difference, trading spread, fund size, securities-lending policy, currency treatment, and tax considerations. Small deviations from the index are normal because the fund has costs and operational constraints. What matters is whether it delivers the promised exposure reliably and cheaply enough for the account in which you hold it.'
    ], [
      ['Does an index fund own every company?', 'Only the securities included under its index rules. Some cover one country, sector, company size, factor, or asset class. Even a total-market index has eligibility and weighting rules. Read the holdings and methodology before assuming it represents the whole world.'],
      ['Is index investing completely passive?', 'The investor still chooses the index, asset allocation, contribution rate, rebalancing rule, and account. The index provider also makes rule-based decisions. Passive usually means the fund follows a published benchmark instead of asking a manager to select holdings case by case.'],
      ['What is tracking difference?', 'It is the gap between a fund\'s return and the return of its benchmark over a period. Fees, taxes, sampling, cash balances, and trading can create the difference. A consistently small gap can be more informative than the headline fee alone.']
    ]),

    'active-vs-passive': depth([
      'Define the comparison before looking at performance. The active fund and benchmark should cover similar assets, geography, company size, and risk. Use returns after all recurring costs and examine several market environments. A manager who owns smaller companies should not be judged against a large-company index, and a strong single year cannot establish repeatable skill.',
      'Write down why active management is being used. Possible reasons include a specific risk-control mandate, access to a less efficient market, tax management, or a service relationship that supports the wider plan. Then identify the evidence and review date. A broad low-cost passive portfolio is a strong default because cost and exposure are knowable; active management carries the added burden of proving that its role justifies higher cost and monitoring.'
    ], [
      ['Can an active manager beat an index?', 'Yes, some do over particular periods. The challenge is identifying them in advance, after fees, and distinguishing skill from luck. Persistence is difficult, which is why a process should not rely on choosing next decade\'s winner from last decade\'s rankings.'],
      ['Does passive investing guarantee average returns?', 'An index fund aims to track its benchmark before costs, not guarantee a gain. The benchmark itself can fall, and the fund will usually trail it slightly after expenses. Average refers to market exposure, not a smooth or risk-free result.'],
      ['Can I combine active and passive funds?', 'Yes. A core broad-market allocation can sit beside a smaller active position with a clearly defined purpose and limit. Measure the combined fees, overlap, and risk so the satellite holding does not quietly replace the diversified core.']
    ]),

    'diversification': depth([
      'Diversify across independent sources of return, not just product names. Look through funds to the underlying companies, countries, currencies, sectors, bond issuers, maturities, and asset classes. Five Canadian bank funds do not create five distinct economic exposures. A globally diversified stock fund plus suitable fixed income may be simpler and broader than a shelf full of overlapping products.',
      'Test diversification under stress. Correlations can rise during a crisis, so no mix eliminates loss. The purpose is to prevent one company, sector, country, or forecast from deciding the entire outcome and to create assets that can be rebalanced. Set concentration limits and review the portfolio as a whole; a position that began small can become the dominant risk after strong performance.'
    ], [
      ['How many funds do I need?', 'Possibly only one balanced all-in-one fund, or a small number covering distinct asset classes. More funds can add overlap without adding protection. Judge diversification by underlying exposure and weights, not by the number of account lines.'],
      ['Does diversification reduce returns?', 'It can prevent the portfolio from fully capturing the best-performing single asset, but it also limits damage from the worst. The aim is not to maximize the luckiest possible outcome. It is to improve the chance that the overall plan survives many possible outcomes.'],
      ['Can I diversify away all risk?', 'No. Broad markets can decline together, inflation can affect many assets, and every investment involves some uncertainty. Diversification mainly reduces risks that are specific to one issuer or narrow exposure; it cannot remove economy-wide or market-wide risk.']
    ]),

    'open-brokerage-account': depth([
      'Choose a brokerage by matching features to the intended routine. Confirm regulation and investor-protection arrangements, then compare account fees, trading and currency costs, available investments, recurring purchases, fractional units, transfer support, statements, customer service, and accessibility. A polished app is useful only if the account also handles the investments and records the plan requires.',
      'Secure the account before funding it. Use a unique password, multifactor authentication, trusted contact information where available, and alerts for logins, withdrawals, or profile changes. Start with a small transfer, verify how orders and settlement work, and confirm beneficiary or successor designations where applicable. Avoid enabling margin or options simply because the setup screen offers them; added features create added obligations and risk.'
    ], [
      ['Cash account or margin account?', 'A cash account limits purchases to available funds. A margin account allows borrowing against investments and can trigger interest, forced sales, or losses beyond the original cash. Most beginners building a long-term portfolio do not need leverage to carry out the plan.'],
      ['What happens if my brokerage fails?', 'Client assets are generally held under custody rules rather than as ordinary brokerage property, and protection arrangements may apply, but coverage and exclusions matter. Verify the dealer\'s regulator and current protection details instead of assuming every loss or investment decline is insured.'],
      ['Should I transfer everything at once?', 'A small initial transfer lets you test funding, statements, service, and order entry. For an existing account, compare in-kind versus cash transfers, exit fees, tax consequences, and time out of market. Registered transfers should follow the proper institution-to-institution process.']
    ]),

    'first-investment-framework': depth([
      'Use a fixed order of decisions: goal, date, account, asset mix, then product. Beginning with a ticker reverses the process and makes every later choice defend the product you already wanted. Write the amount needed, the contribution schedule, and how flexible the goal is. Money required within a few years should not depend on the same portfolio as money intended for retirement decades away.',
      'Choose the simplest diversified implementation that meets the need, calculate its complete cost, and automate contributions. Add two rules for difficult periods: when to rebalance and which life changes justify reducing risk. Review once or twice a year. A first portfolio is not a permanent identity; it is a working system that can evolve as income, knowledge, and goals change without reacting to every market headline.'
    ], [
      ['What should my very first investment be?', 'There is no universal ticker. For many beginners, a low-cost diversified fund matched to their time horizon and risk capacity is easier to maintain than individual securities. The correct account and emergency savings position matter before the product choice.'],
      ['Do I need to understand every market detail first?', 'No. You should understand what you own, its main risks, cost, tax account, and role in the goal. A simple diversified approach can begin while learning continues. Complexity should be added only when it solves a specific problem you can explain.'],
      ['How often should I change my portfolio?', 'Change it when the goal, horizon, cash flow, tax situation, risk capacity, or implementation has materially changed, or when a preset rebalance rule applies. New headlines and recent winners are not by themselves reasons to rewrite a long-term plan.']
    ]),

    'how-much-to-invest': depth([
      'Start with cash flow, not an aspirational percentage. Subtract essential spending, minimum debt payments, near-term obligations, and a realistic amount for irregular costs from take-home income. Protect an emergency reserve and capture valuable employer matching where available. The amount left can be divided among goals according to urgency and horizon. A contribution is sustainable only if it survives ordinary months without relying on credit.',
      'Convert the goal into a monthly range and test it under conservative returns. If the target requires too much today, begin lower and create an escalation rule tied to raises, bonuses, or debts ending. Variable earners can automate a modest baseline and direct a percentage of income above that baseline. Review the rate annually; consistency and periodic increases usually matter more than finding one perfect number.'
    ], [
      ['What percentage of income should I invest?', 'Rules of thumb can provide a starting point, but housing, pensions, debt, age, income stability, and goals differ widely. Work backward from the amount and date you need, then compare that requirement with a sustainable cash-flow budget.'],
      ['Should I invest if I have no emergency fund?', 'A small investment can build the habit, but accessible cash usually deserves priority because an unexpected bill could force debt or a sale during a decline. Build the two deliberately rather than treating invested money as an emergency account.'],
      ['What should I do after a raise?', 'Decide before the first larger paycheque. Direct part of the increase to contributions, part to other goals or debt, and keep part for current life. An automatic percentage increase preserves flexibility while preventing the entire raise from disappearing into permanent spending.']
    ]),

    'registered-accounts': depth([
      'Treat an account as a tax container and the investments as its contents. A TFSA, RRSP, FHSA, RDSP, pension, and non-registered account can each hold different eligible assets while applying different contribution, deduction, growth, and withdrawal rules. Choosing an account does not choose the portfolio. First understand the goal and tax treatment; then select suitable investments inside it.',
      'Maintain an account map using current official records. Track available room, contributions, withdrawals, carry-forward rules, beneficiary details, employer matching, and any deadlines relevant to the goal. Do not rely solely on a financial institution display because it may not include activity elsewhere or recent transactions. When moving a registered account, use the proper direct-transfer process so the movement is not accidentally treated as a withdrawal.'
    ], [
      ['Which registered account should I fill first?', 'It depends on income, employer matching, home-buying plans, disability eligibility, retirement needs, benefits, and expected future tax rates. Capture employer matching first when appropriate, then compare each account against the next specific goal rather than following one universal sequence.'],
      ['Can registered accounts hold cash and investments?', 'Many can hold savings products, guaranteed investments, bonds, funds, and other qualified investments, depending on the provider. The account label describes tax rules; the chosen holding determines market risk, return, liquidity, and fees.'],
      ['Why should I verify contribution room myself?', 'Overcontributions can create tax and administrative problems. Room can be affected by activity at multiple institutions and may not update instantly in government records. Keep your own ledger and confirm current rules with the responsible agency before a large contribution.']
    ]),

    'automatic-contributions': depth([
      'Design automation around the real pay cycle. Schedule the transfer shortly after income arrives, leave enough buffer to avoid overdraft, and send money directly to the account attached to the goal. Confirm whether the provider invests the cash automatically or merely deposits it. Uninvested balances can accumulate quietly even while the savings habit appears to be working.',
      'Add guardrails so automation remains helpful. Set alerts for failed transfers, review the amount after income changes, and keep a clear pause rule for job loss or a genuine cash emergency. Add a small annual increase or direct part of each raise to the schedule. The purpose is to reduce routine decisions, not to make the system invisible; a brief quarterly check catches errors without inviting constant tinkering.'
    ], [
      ['What if the market is down on my contribution date?', 'The schedule is meant to continue through different market conditions. A lower price buys more units. Change the contribution because your cash flow or goal changed, not because one scheduled date happens to coincide with frightening headlines.'],
      ['Should transfers happen weekly or monthly?', 'Match them to when income arrives and minimize fees or operational friction. The difference between sensible frequencies is usually much smaller than the effect of the amount, costs, investment choice, and ability to continue for years.'],
      ['Can I automate too much?', 'Yes. A transfer that repeatedly causes overdraft, credit-card borrowing, or emergency withdrawals is too aggressive. Keep a chequing buffer and review irregular bills. Automation should stabilize the plan rather than make each month fragile.']
    ]),

    'beginner-investing-mistakes': depth([
      'Most early mistakes are system problems rather than intelligence problems. A missing emergency fund creates forced sales; an undefined goal makes every product look plausible; a complicated portfolio makes maintenance easy to avoid; and constant media exposure turns normal volatility into a stream of urgent decisions. Fix the environment before trying to improve prediction skill.',
      'Use a pre-trade checklist and a waiting period for unplanned changes. Confirm the goal, account, asset allocation, diversification, complete cost, tax effect, and maximum loss. Write down why the change improves the whole portfolio. Review outcomes based on process, not whether a gamble happened to work. A boring system with clear defaults is often more resilient than a clever collection of disconnected ideas.'
    ], [
      ['What is the most damaging beginner mistake?', 'Taking risk with money needed soon can force a sale at the worst time. Concentration, leverage, fraud, and high recurring fees can also cause lasting damage. The common thread is allowing one decision to threaten an essential goal.'],
      ['Should I wait until I know more?', 'Learn enough to understand the account, diversified investment, costs, risks, and goal. Then a small, simple start can teach more than indefinite observation. Avoid using education as a reason to postpone forever or confidence as a reason to begin with complexity.'],
      ['How do I recover from a poor investment decision?', 'Stop adding money automatically, reassess the thesis without anchoring to the purchase price, and examine tax and transaction consequences. Decide what you would choose if the position were cash today. Then rebuild around the goal and document the lesson without trying to win the loss back quickly.']
    ]),

    'bear-markets': depth([
      'Prepare for a bear market while prices are calm. Decide how much spending belongs in cash or short-term high-quality assets, set target allocation ranges, and write the contribution and rebalancing rules. Translate a possible decline into dollars so the chosen risk is concrete. If a routine market loss would force a home sale, tuition delay, or expensive debt, the portfolio and goal are mismatched before the decline begins.',
      'During a downturn, separate market facts from household facts. Check employment, emergency savings, upcoming withdrawals, debt, and concentration. Then compare current weights with the plan. Continuing contributions or rebalancing may be appropriate when the goal is unchanged, but a real loss of income or newly fixed deadline can justify reducing risk. Avoid making a macroeconomic forecast do the job of a cash-flow review.'
    ], [
      ['How long does a bear market last?', 'There is no dependable schedule. Declines and recoveries vary widely, and the economy can feel weak even after markets begin recovering. Build the plan so an exact recovery date is not required for near-term spending.'],
      ['Should I buy more after a large decline?', 'Only within the planned allocation and after protecting cash needs. Rebalancing or continuing scheduled contributions can add exposure at lower prices. Borrowing, concentrating, or emptying emergency savings because the market looks cheap creates a different and potentially dangerous bet.'],
      ['What if this downturn really is different?', 'Every downturn has distinct causes, but uncertainty and loss are already part of owning risky assets. Ask whether the long-term goal, diversification, liquidity, or financial system assumptions have changed in a way your policy addresses. Do not let the uniqueness of the story erase basic risk controls.']
    ]),

    'tfsa-explained': depth([
      'Use a TFSA according to the goal, not the name. It can hold cash for near-term needs or investments for long-term growth, depending on the provider and eligible holdings. Because qualified withdrawals are generally tax-free and do not produce a deduction when contributed, the account can be valuable across income levels. The risk still comes from what is held inside it.',
      'Keep a contribution ledger across every TFSA. Record deposits, withdrawals, transfers, and the room you relied on before each transaction. A withdrawal generally creates new room in a later calendar year rather than immediately, so recontributing too soon can cause an excess amount. Verify current room and residency rules with the CRA, especially after large withdrawals, multiple accounts, or time outside Canada.'
    ], [
      ['Should my emergency fund be in a TFSA?', 'It can be when room is available, the provider offers suitable access, and the money is held in a stable product. Compare withdrawal timing and whether using room for cash prevents long-term investments from receiving the same tax shelter. The account and the asset are separate choices.'],
      ['Do TFSA withdrawals count as taxable income?', 'Qualified withdrawals are generally not included in taxable income, which can make the account flexible for future spending. Rules and benefit interactions should still be verified for unusual circumstances, and investment losses do not restore contribution room.'],
      ['Can I have more than one TFSA?', 'Yes, but contribution room is shared across all of them. Multiple institutions do not create multiple limits. A personal ledger is essential because one provider may not know what you contributed or withdrew elsewhere.']
    ]),

    'rrsp-explained': depth([
      'Think of an RRSP as a tax-timing tool for retirement, not simply a place to collect a refund. Contributions may create a deduction, growth is tax-deferred while it remains in the plan, and withdrawals are generally taxable income. The potential advantage depends on the tax rate when the deduction is claimed, the tax rate when money is withdrawn, the years of sheltered compounding, and what happens to the tax saving.',
      'Build an RRSP plan alongside the eventual withdrawal plan. Track contribution room, employer or pension adjustments, beneficiary details, and any programs that allow specific withdrawals under current rules. Model retirement income from all sources so RRSP or RRIF withdrawals do not arrive as a surprise. When income is temporarily low, claiming a deduction later may be worth investigating, but verify the current rules and your personal tax situation before acting.'
    ], [
      ['Should I spend or invest my RRSP tax refund?', 'If the contribution was sized assuming the refund would be invested or used for debt, spending it reduces the strategy\'s benefit. Decide before filing. Reinvesting the refund can increase total retirement savings, while paying expensive debt can improve cash flow and reduce guaranteed interest cost.'],
      ['Is an RRSP withdrawal penalized?', 'Ordinary withdrawals are generally included in taxable income, and the institution normally withholds part for tax. The withholding is not necessarily the final tax bill. Unlike a TFSA withdrawal, withdrawn RRSP room is generally not restored, subject to specific program rules.'],
      ['Is an RRSP only useful in a high tax bracket?', 'A higher current deduction rate can increase its value, but time, employer matching, future income, benefits, and retirement tax rates also matter. Lower-income savers may still benefit, while sometimes preferring TFSA flexibility. Compare the full household timeline rather than one year alone.']
    ]),

    'tfsa-vs-rrsp': depth([
      'Compare the accounts using the same dollar of before-tax income. An RRSP contribution can create a deduction but future withdrawals are generally taxable. A TFSA contribution uses after-tax money and qualified withdrawals are generally tax-free. If the tax rate is the same at contribution and withdrawal and the RRSP tax saving is also invested, the mathematical outcomes can be similar. Differences in rates, flexibility, benefits, and behaviour create the practical result.',
      'Assign each account to a job. TFSA flexibility can suit uncertain goals, emergency overflow, or retirement spending that should not add taxable income. RRSP room can be especially valuable with employer matching or when deductions are claimed at a meaningfully higher rate than expected withdrawals. Many households should use both over time. Revisit the split after income, province, benefits, home plans, or retirement projections change.'
    ], [
      ['Which account should a beginner open first?', 'Start with employer matching if available, then consider income, deduction value, contribution room, withdrawal flexibility, and the goal. A lower-income person expecting higher future earnings may value TFSA flexibility, while a strong current deduction can favour the RRSP.'],
      ['Can I hold the same investments in both?', 'Often yes, if the investments are qualified and offered by the provider. The asset mix should follow the goal and total household portfolio. Account tax rules can influence location, but they do not make an unsuitable investment suitable.'],
      ['Do TFSA and RRSP limits reset every year?', 'New room may arise under their respective rules, but unused room, withdrawals, pension adjustments, and prior contributions affect the amount differently. Check current official records and keep a personal ledger rather than treating each January as a clean slate.']
    ]),

    'fhsa-explained': depth([
      'Connect an FHSA to a realistic home timeline. Contributions may be deductible and a qualifying home withdrawal can be tax-free under current rules, which combines features associated with RRSPs and TFSAs. The investment inside should still match when the money may be needed. A purchase expected in two years calls for much less market risk than a flexible plan eight or ten years away.',
      'Track the account opening date, annual participation room, lifetime contributions, transfers, and qualifying-withdrawal conditions using current CRA guidance. Opening the account can affect when room begins to accumulate, so timing matters. Also plan for the possibility that no home is purchased: understand the permitted transfer or withdrawal paths and deadlines before contributing. Tax benefits should support the housing plan, not pressure you into a purchase you cannot comfortably carry.'
    ], [
      ['What can I invest in inside an FHSA?', 'Providers may offer cash, guaranteed products, funds, and other qualified investments. Choose based on purchase horizon and flexibility. The account\'s tax treatment does not protect a stock fund from falling shortly before a down payment is due.'],
      ['Can I use an FHSA and the Home Buyers\' Plan?', 'Current rules may allow both when their separate conditions are met. They work differently: an FHSA qualifying withdrawal is not generally repaid, while the Home Buyers\' Plan involves an RRSP withdrawal with repayment requirements. Verify limits and eligibility before coordinating them.'],
      ['What if I never buy a home?', 'The rules provide potential paths such as a qualifying transfer to certain retirement plans, subject to conditions and deadlines. A taxable withdrawal may also be possible. Review current CRA guidance well before the account\'s maximum participation period ends.']
    ]),

    'cpp-explained': depth([
      'Treat CPP as one layer of retirement income rather than the entire plan. Your pension depends on contribution history, pensionable earnings, exclusions or provisions that apply, and the age benefits begin. Obtain your official contribution statement and estimate, then combine it with Old Age Security, workplace pensions, registered accounts, taxable savings, housing costs, and the desired retirement budget.',
      'The start-age decision is a longevity and cash-flow choice, not a contest to identify one universally best age. Starting earlier provides smaller payments sooner; delaying within the permitted range increases the monthly amount. Compare cumulative income under several lifespans, the need for income now, health, survivor considerations, taxes, and whether drawing from savings temporarily would improve long-term guaranteed income. Verify the current adjustment rates before deciding.'
    ], [
      ['Is my CPP estimate guaranteed?', 'An official estimate is more useful than a generic average, but future contributions, earnings, start age, and rule changes can affect the final amount. Review the contribution record for errors and update the retirement projection periodically.'],
      ['Should everyone delay CPP to age 70?', 'No. Delaying can provide a larger inflation-adjusted monthly payment, but health, cash needs, employment, other assets, taxes, and personal preference matter. The right comparison is how each start age supports the complete retirement plan under multiple lifespans.'],
      ['Can I receive CPP while still working?', 'It may be possible, and contributions or post-retirement benefits can apply depending on age and circumstances. Employment income can also affect tax planning. Check current Service Canada rules for the exact situation rather than assuming work and CPP are mutually exclusive.']
    ]),

    'disability-investing-canada': depth([
      'Begin with eligibility and available support, not the investment menu. An RDSP can provide long-term tax-deferred growth and may attract Canada Disability Savings Grants or Bonds under current rules. Access commonly depends on Disability Tax Credit eligibility, and grant or bond amounts can depend on family income, contributions, age, and prior entitlements. Verify these details before deciding how much personal money to add.',
      'Coordinate the RDSP with immediate accessibility costs, emergency savings, provincial or territorial benefits, trusts, insurance, estate plans, and the beneficiary\'s decision-making support. Withdrawal rules can be complex, including repayment consequences tied to recent government assistance. Keep a timeline of contributions, grants, bonds, and planned withdrawals, and involve a qualified disability-planning professional when the amounts or benefit interactions are significant.'
    ], [
      ['Is an RDSP only for families with money to contribute?', 'No. The Canada Disability Savings Bond may be available to eligible lower-income beneficiaries without a personal contribution, under current rules. Grants can also increase qualifying contributions. Eligibility, age, and income details should be confirmed with official sources.'],
      ['Can RDSP money be used for any purpose?', 'Payments are intended for the beneficiary, but the plan has detailed withdrawal formulas, tax treatment, and possible assistance-repayment rules. Ask the provider for a written illustration before a withdrawal so the net payment and consequences are understood.'],
      ['How should an RDSP be invested?', 'Match the holdings to the beneficiary\'s time horizon, expected withdrawal pattern, risk capacity, and wider support system. Government incentives do not eliminate market risk. Money needed soon may require stability, while very long-term funds may support a diversified growth allocation.']
    ]),

    'investor-behaviour': depth([
      'Improve behaviour by changing the decision environment. Reduce price alerts and financial-news checks, automate ordinary contributions, and keep the long-term allocation where it is easy to see. Require a written reason and a cooling-off period for any unplanned trade. Friction is helpful when it stands between an emotion and an irreversible action, while automation is helpful for decisions already made in calm conditions.',
      'Keep a decision journal with the date, available evidence, alternatives, expected outcome, confidence range, and conditions that would change the plan. Review it later without judging only the profit or loss. Outcome bias can praise a reckless win and condemn a thoughtful decision that met an unlucky result. The goal is not emotionless investing; it is a process that still functions when fear, excitement, and social proof are strongest.'
    ], [
      ['What is loss aversion?', 'People often feel the pain of a loss more strongly than the pleasure of an equal gain. That can lead to selling after declines, avoiding appropriate risk, or holding a losing position merely to avoid admitting the loss. Written rules reduce the need to improvise.'],
      ['How can I avoid chasing performance?', 'Compare any proposed purchase with the existing goal and allocation, then ask what price and evidence would have supported it before the recent rise. Use a waiting period and review longer histories, costs, valuation, and overlap. Recent return alone is not an investment thesis.'],
      ['Does checking my portfolio often cause harm?', 'Checking is not automatically harmful, but frequent observation exposes you to more negative intervals and more temptation to act. Match monitoring to the decisions required. A diversified long-term portfolio may need occasional review, while account security alerts should remain immediate.']
    ]),

    'asset-allocation': depth([
      'Set asset allocation at the goal level. Estimate the amount, date, flexibility, contribution capacity, and spending pattern, then decide how much belongs in growth assets, stabilizing assets, and cash. Stocks can support long-term growth but fluctuate sharply; high-quality bonds can provide income and rebalancing capacity but also move; cash protects near-term obligations while sacrificing long-run return.',
      'Test the mix in dollars. If stocks fell substantially and bonds also declined modestly, could the goal continue without selling essential assets? Include income security, pensions, debts, and housing rather than treating the brokerage account in isolation. Write target weights and acceptable ranges, then choose funds that implement them. Change the allocation for a changed goal or capacity, not because one asset class recently performed well.'
    ], [
      ['What is the best stock-to-bond ratio?', 'There is no universal ratio. Time horizon, withdrawal needs, job stability, pension income, goal flexibility, and emotional tolerance all matter. The best mix is aggressive enough to make the goal feasible and conservative enough that you can hold and fund it through a severe decline.'],
      ['Should allocation become safer with age?', 'Age is a useful clue but not the full answer. The timing of withdrawals, guaranteed income, portfolio size, bequest goals, and flexibility matter more directly. A gradual shift may be appropriate as a goal approaches, based on its actual cash-flow needs.'],
      ['Do all-in-one funds solve allocation?', 'They can provide a diversified preset mix and automatic rebalancing in one product. You still need to select the right risk level, understand the underlying exposure and cost, and avoid combining it with other holdings that unintentionally change the total mix.']
    ]),

    'rebalancing': depth([
      'Choose one rebalancing method in advance. A calendar rule checks the portfolio on set dates; a threshold rule acts when an asset moves outside a stated band; a hybrid checks periodically and trades only when a band is breached. The method matters less than applying it consistently. Very narrow bands can create unnecessary trading, while no rule allows yesterday\'s winner to determine tomorrow\'s risk.',
      'Use the least disruptive tool first. Direct new contributions, dividends, or withdrawals toward underweight or overweight assets before selling. In taxable accounts, consider realized gains, losses, superficial-loss rules, and transaction costs. Rebalance the household portfolio as a whole when practical, including workplace plans. The aim is to restore the planned risk, not to predict which asset will lead next.'
    ], [
      ['Does rebalancing increase returns?', 'It is primarily a risk-control process. It may add or subtract return depending on market patterns. Its dependable function is preventing allocation drift and requiring a disciplined sell-high, buy-low action relative to the chosen target.'],
      ['How often should I rebalance?', 'Many plans use an annual or semi-annual review, threshold bands, or both. The best interval balances meaningful risk drift against taxes, costs, and effort. Daily monitoring usually adds noise without improving a long-term policy.'],
      ['Should I rebalance during a market crash?', 'Follow the preset rule after confirming cash needs and that the target allocation remains suitable. Rebalancing can involve buying the asset that fell, which may feel uncomfortable. Do not add leverage or use emergency money simply to force the percentages back into place.']
    ]),

    'bonds-in-portfolio': depth([
      'Define what the bond allocation must do. It may fund near-term withdrawals, reduce total volatility, produce income, diversify stock risk, or provide assets to rebalance after an equity decline. Different bonds serve those purposes differently. Short government debt emphasizes stability; long bonds carry more interest-rate sensitivity; lower-quality credit may behave more like stocks during stress.',
      'Review duration, credit quality, currency, yield, fees, and the maturity profile rather than purchasing on yield alone. Decide whether known individual maturities or an ongoing diversified fund better match the goal. A bond allocation can decline and may not offset stocks in every period, but that does not make it useless. Judge it by its assigned role across the full plan, not by whether it won the latest calendar year.'
    ], [
      ['Why own bonds when stocks have higher expected returns?', 'A portfolio must be survivable, not merely maximize an average forecast. Bonds can reduce the amount that must be sold from stocks during a decline, support rebalancing, and better match nearer obligations. The trade-off is lower expected long-term return.'],
      ['Can bonds and stocks fall together?', 'Yes. Inflation shocks, rapid interest-rate changes, or credit stress can pressure both. Diversification does not require perfect opposite movement every month. The degree of decline, income, maturity, and recovery path can still differ meaningfully.'],
      ['Is a high-yield bond a stock substitute?', 'Lower-quality bonds offer contractual payments but carry greater default and economic risk, and they can decline with equities during stress. Treat the extra yield as compensation for credit risk and avoid placing them in the safest portfolio bucket without examining that behaviour.']
    ]),

    'inflation-erodes-savings': depth([
      'Express long-term goals in today\'s purchasing power and future dollars. Estimate how major categories such as housing, food, health care, and travel might change, recognizing that personal inflation can differ from the national index. Then show investment returns after assumed inflation. A portfolio growing 5% while costs rise 3% is not creating 5% more lifestyle.',
      'Use a layered response. Keep near-term money stable, seek competitive interest where appropriate, and give long-term money enough diversified growth exposure to have a chance of outpacing rising costs. Consider whether wages, pensions, rents, or benefits adjust with inflation. Review the spending target rather than reacting to one high-inflation year by taking excessive risk or abandoning all cash.'
    ], [
      ['Why does inflation feel higher than the reported number?', 'A price index represents a broad basket and population average. Your spending weights may be concentrated in categories rising faster, such as rent or food. Track the costs that dominate your own budget while using official measures for a consistent economy-wide reference.'],
      ['Do stocks always protect against inflation?', 'No. Businesses can sometimes raise prices and grow earnings over long periods, but valuations and profits can fall during inflation shocks. Stocks are volatile and are not a dependable short-term inflation hedge for money needed soon.'],
      ['Should I change my return target when inflation rises?', 'Separate nominal and real assumptions. Higher nominal returns do not necessarily improve purchasing power if inflation also rises. Re-run the plan with several real-return and spending scenarios, then adjust controllable inputs rather than assuming markets will automatically compensate.']
    ]),

    'index-vs-active-funds': depth([
      'Build a like-for-like comparison sheet. Record each fund\'s mandate, benchmark, geography, asset class, company-size exposure, concentration, cash position, expense ratio, advice charge, and ten-year survival where available. Then compare rolling and long-period returns after fees, not only the best calendar year shown in marketing. A fair benchmark should resemble what the manager was actually allowed to own.',
      'Define the decision rule before selecting an active fund. State what evidence supports manager skill, how much underperformance you will tolerate, and which changes in people, process, fees, or portfolio would trigger review. Without that policy, investors often buy after outperformance and sell after underperformance. An index fund also needs review for tracking and fit, but it avoids the ongoing task of deciding whether a manager\'s disappointing period is patience-worthy skill or ordinary failure.'
    ], [
      ['How long should I give an active manager?', 'There is no universally correct period because strategies differ, but one or two years can be dominated by style cycles and luck. Review whether the stated process, team, holdings, risk, and cost remain intact, while evaluating results over multiple relevant market conditions.'],
      ['What does survivorship bias mean for fund comparisons?', 'Poor funds may merge or close and disappear from a current list, making the surviving group look stronger than the original choices investors faced. Research that includes liquidated and merged funds provides a fairer picture of manager-selection difficulty.'],
      ['Can an index fund underperform its benchmark?', 'Yes, usually by costs and implementation differences. Taxes, sampling, trading, cash, and securities lending can affect tracking. Compare the actual tracking difference over time, not only the advertised management fee.']
    ]),

    'expense-ratios-mers': depth([
      'Translate every recurring percentage into current and future dollars. Multiply the rate by the balance for a rough annual figure, then model the cost over the holding period because fees also remove money that could have compounded. Compare products on the same asset exposure and service level. A 1% difference on a growing portfolio is not a one-time 1% charge; it repeats on each year\'s balance.',
      'Go beyond the MER. Add trading expenses inside the fund, adviser or platform charges, account administration, commissions, bid-ask spreads, and foreign-exchange costs. Ask whether quoted performance is already net of the internal fund expense and which external charges remain. If a higher-cost option provides planning or specialized management, describe that value in concrete services and review it annually rather than assuming price alone proves quality.'
    ], [
      ['How is an MER actually charged?', 'It is generally deducted within the fund rather than appearing as a separate monthly bill, so published fund returns normally reflect it. The fund\'s value grows by less than it otherwise would. External account or advice fees may appear separately.'],
      ['What is the difference between MER and management fee?', 'The management fee pays the manager and related services, while the MER is a broader measure that generally includes the management fee plus certain operating expenses and taxes. Trading expenses can be reported separately. Check the fund documents for exact composition.'],
      ['When does switching to a cheaper fund make sense?', 'Compare the ongoing saving with taxes, redemption charges, transfer fees, spreads, time out of market, and differences in exposure or service. A clearly lower recurring cost can be valuable, but the replacement must still implement the same plan.']
    ]),

    'market-drops-plan': depth([
      'Use a written decline checklist before opening the trading screen. Confirm that essential bills and emergency savings are covered, list withdrawals due in the next few years, and compare the portfolio with its target weights. Check for leverage or a single position that creates forced action. If the household facts and allocation remain sound, the plan may call for continued contributions, measured rebalancing, or no trade at all.',
      'Control the information flow. Choose one or two reliable sources, avoid repeatedly refreshing prices, and require a cooling-off period for any sale not already in the policy. Contact the brokerage directly if an account message creates urgency; market fear attracts impersonation and recovery scams. After conditions stabilize, review whether the allocation produced more stress or cash-flow risk than expected and make any permanent change deliberately.'
    ], [
      ['Should I sell to stop the loss and buy back later?', 'That requires two successful timing decisions. A recovery can begin while news remains terrible, leaving no comfortable re-entry point. Sell when the goal, liquidity, or suitable allocation changed, not merely because a temporary loss became visible.'],
      ['What should a retiree check first?', 'Confirm the next several years of withdrawals, pension and other income, tax needs, and which assets can fund spending without a distressed stock sale. Sequence risk makes near-term liquidity and withdrawal flexibility especially important.'],
      ['What if my portfolio falls more than I expected?', 'Pause and translate the loss into the goal impact. It may reveal that the original risk estimate was unrealistic. Protect immediate needs first, then redesign the long-term allocation once, rather than alternating between panic and renewed risk as prices move.']
    ]),

    'budgeting-without-rigidity': depth([
      'Use four broad lanes instead of dozens of fragile categories: fixed commitments, true expenses, future goals, and flexible spending. True expenses are predictable but irregular costs such as repairs, insurance, gifts, and annual fees; divide them into monthly sinking-fund amounts. Automate bills and goals after each paycheque, then treat the remaining weekly amount as genuinely available rather than requiring a moral judgment for every purchase.',
      'Review the system with curiosity, not punishment. Compare actual totals with the plan once a week or month and adjust the structure when the same mismatch repeats. Variable earners can build fixed commitments around a conservative income baseline, save a percentage of higher months, and maintain a larger buffer. A budget is successful when it makes trade-offs visible and prevents emergencies, even if individual categories move around.'
    ], [
      ['What if I hate tracking every transaction?', 'Track account-level totals and automate the important lanes. One flexible spending account or weekly transfer can limit discretionary spending without categorizing each coffee. Periodically scan statements for errors, subscriptions, and unusual changes.'],
      ['How do I budget for irregular expenses?', 'List annual and seasonal costs, estimate the yearly total, and divide it into a monthly sinking-fund contribution. Keep the money separate enough that it is not mistaken for everyday spending. Update estimates after the real bill arrives.'],
      ['Where should investing appear in a budget?', 'Treat goal contributions as a planned transfer after essential stability and minimum obligations, not as whatever remains accidentally. The amount should be sustainable and can increase over time. Keep emergency savings and long-term investing separate because they solve different problems.']
    ])
  };
}());
